#ifndef DEF_PINNACLE_H
#define DEF_PINNACLE_H

#define DATA_SVALA_SORROWGRAVE_EVENT    1
#define DATA_GORTOK_PALEHOOF_EVENT      2
#define DATA_SKADI_THE_RUTHLESS_EVENT   3
#define DATA_KING_YMIRON_EVENT          4

#define DATA_SVALA_SORROWGRAVE          10
#define DATA_GORTOK_PALEHOOF            11
#define DATA_SKADI_THE_RUTHLESS         12
#define DATA_KING_YMIRON                13

#define DATA_MOB_FRENZIED_WORGEN        20
#define DATA_MOB_RAVENOUS_FURBOLG       21
#define DATA_MOB_MASSIVE_JORMUNGAR      22
#define DATA_MOB_FEROCIOUS_RHINO        23

#endif
